# Generated by Django 2.2.1 on 2019-06-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dj',
            new_name='Test',
        ),
    ]
